//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youfan_Invoicing_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dep> dep { get; set; }
        public virtual DbSet<emp> emp { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<order_model> order_model { get; set; }
        public virtual DbSet<order_type> order_type { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_type> product_type { get; set; }
        public virtual DbSet<relation_emp_menu> relation_emp_menu { get; set; }
        public virtual DbSet<relation_role_menu> relation_role_menu { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<store_detail> store_detail { get; set; }
        public virtual DbSet<store_log> store_log { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
    
        public virtual ObjectResult<proc_SelAll_Result> proc_SelAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_SelAll_Result>("proc_SelAll");
        }
    }
}
