//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youfan_Invoicing_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int order_detail_id { get; set; }
        public Nullable<int> detail_num { get; set; }
        public Nullable<decimal> detail_price { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> order_type_id { get; set; }
    
        public virtual order_type order_type { get; set; }
        public virtual product product { get; set; }
    }
}
