//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youfan_Invoicing_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_model()
        {
            this.store_log = new HashSet<store_log>();
        }
    
        public int order_id { get; set; }
        public string order_num { get; set; }
        public Nullable<int> creater { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<int> checker { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public string OutIn_number { get; set; }
        public Nullable<int> order_type_id { get; set; }
        public Nullable<bool> order_state { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> total_num { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> supplier_id { get; set; }
    
        public virtual emp emp { get; set; }
        public virtual emp emp1 { get; set; }
        public virtual order_type order_type { get; set; }
        public virtual product product { get; set; }
        public virtual supplier supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<store_log> store_log { get; set; }
    }
}
