//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youfan_Invoicing_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_detail = new HashSet<order_detail>();
            this.order_model = new HashSet<order_model>();
            this.store_detail = new HashSet<store_detail>();
        }
    
        public int product_id { get; set; }
        public Nullable<int> product_type_id { get; set; }
        public string product_name { get; set; }
        public string producer { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> in_price { get; set; }
        public Nullable<int> pro_Inventory { get; set; }
        public Nullable<bool> Shelves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_model> order_model { get; set; }
        public virtual product_type product_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<store_detail> store_detail { get; set; }
    }
}
