//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Youfan_Invoicing_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_log
    {
        public int log_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<System.DateTime> oper_time { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> order_type_id { get; set; }
    
        public virtual emp emp { get; set; }
        public virtual order_model order_model { get; set; }
        public virtual order_type order_type { get; set; }
    }
}
